### ISSUE TITLE
Rack Gem Version Compatibility

### ISSUE THREAD

**Issue by tomprats** [intridea/oauth2#229]
I'm using oath2 in an application (through Twitter, Facebook, and Instagram) and I was hoping to upgrade to Rails 5 (beta). When doing so, I ran into a dependency problem. It looks like version 2 of Rack isn't released yet, but is trusted enough to be used in Rails 5.

I noticed there haven't been any commits for over a year, but would it be possible to update the dependencies? I can look into what the 2.0 changes include and possibly create a pull request, but I have pretty limited knowledge of this gem.

```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    rails (>= 0) ruby depends on
      railties (= 5.0.0.beta1) ruby depends on
        actionpack (= 5.0.0.beta1) ruby depends on
          rack (~> 2.x) ruby

    rails (>= 0) ruby depends on
      railties (= 5.0.0.beta1) ruby depends on
        actionpack (= 5.0.0.beta1) ruby depends on
          rack-test (~> 0.6.3) ruby depends on
            rack (>= 1.0) ruby

    omniauth-facebook (~> 3.0) ruby depends on
      omniauth-oauth2 (~> 1.2) ruby depends on
        oauth2 (~> 1.0) ruby depends on
          rack (~> 1.2) ruby

    rack (>= 0) ruby
```

**Comment by prathamesh-sonpatki** [comment]
There is already a PR for Rack 2 support - https://github.com/intridea/oauth2/pull/226

**Comment by tomprats** [comment]
Awesome, thanks! I searched the issues for Rack but I forgot to search PRs
