### ISSUE TITLE
Can we publish version with support of rack 2 to rubygems

### ISSUE THREAD

**Issue by Hirurg103** [intridea/oauth2#235]
There is an issue NoamB/sorcery#742 which requires version of oauth 2 compatible with rack 2. Support for rack 2 is now added on master. Can we publish this fix to rubygems?

**Comment by bquorning** [comment]
I was going to ask the same thing. I am preparing a bunch of internal gems for Rails 5 compatibility, and ran into this Rack ~>1.2/~>2.0 issue.

**Comment by oliverzeyen** [comment]
:+1:

**Comment by airblade** [comment]
This has tripped me up too.

**Comment by bquorning** [comment]
@sferik Is there anything missing before a new version can be released? Anything we can do to help?

**Comment by bquorning** [comment]
Thank you! :heart:

**Comment by twe4ked** [comment]
For those following along at home [a new version](https://rubygems.org/gems/oauth2/versions/1.1.0) has been released.

**Comment by Hirurg103** [comment]
@twe4ked thank you. yea, [the new version](https://github.com/intridea/oauth2/commit/90262ae7ebb447da443b80df361ffcaa3a564343) (1.1.0) was released 2 days ago

**Comment by airblade** [comment]
Thank you!
