### ISSUE TITLE
site url getting overridden 

### ISSUE THREAD

**Issue by anand9** [intridea/oauth2#241]
I have my site url as 
`site          = "https://192.168.5.15:9443/oauth2/authorize"`
but once i call `client.auth_code.authorize_url(:redirect_uri => redirect_uri)` my url is changed to 
`https://192.168.5.15:9443/oauth/authorize?client_id=J7H_LoEIdaf9aVXF_opqtVMLgwoa&redirect_uri`

So my oauth2/authorize is being replaced by oauth/authorize

Is there any way to fix this?

**Comment by anand9** [comment]
Figured out the answer
You need to pass the `:authorize_url` attribute.
`require 'oauth2'
client = OAuth2::Client.new('client_id', 'client_secret', :authorize_url => '/oauth2/authorize', :site => 'https://192.168.5.15:9443')`

**Comment by KelseyDH** [comment]
This needs to be in the documentation!

**Comment by pboling** [comment]
@KelseyDH Please submit a PR if you have time :)
