### ISSUE TITLE
State in auth_code.authorize_url

### ISSUE THREAD

**Issue by ivanstojkovicapps** [intridea/oauth2#272]
Hi,

is there a way to pass state in auth_code.authorize_url ?

best regards Ivan

**Comment by josephpage** [comment]
For sure !
Very simple :

```
client.auth_code.authorize_url({ redirect_uri : 'http://localhost:3000', state: 'foo' })
```

If the Oauth2 server implement the feature too,
you will be redirected to `http://localhost:3000?code=xx..xx&state=foo`

It works perfectly in my case.

**Comment by josephpage** [comment]
Hi @ivanstojkovicapps, can you please close the issue if solved for you ?
