### ISSUE TITLE
Is it possible to update Faraday gem to 0.11?

### ISSUE THREAD

**Issue by kirikak2** [intridea/oauth2#290]
I have a problem using OAuth2 gem under proxy environment.
My environment using HTTP_PROXY and HTTPS_PROXY variables, and I tried to connect OAuth2 provider on localhost.
However, It failed to connect. because my access through the proxy server, and It cannot reach OAuth2 provider on localhost.

To solve this problem, OAuth2 gem should support NO_PROXY variable.
Recent, Faraday supports NO_PROXY environment in 0.11, but OAuth2 gem do not support Faraday 0.11.  lostisland/faraday#658

Is it possible to update Faraday 0.11?

**Comment by Darhazer** [comment]
Another reason to update Faraday is that `twitter` gem, v 6.1.0 depends on faraday 0.11, and `oauth2` locks to older version

**Comment by danielbonnell** [comment]
I would also greatly appreciate bumping up to Faraday 0.11 as the current lock on 0.10 is causing me a lot of problems.

**Comment by morgoth** [comment]
Faraday 0.11 fixes Ruby 2.4.0 warnings - would be great to update it in oauth2

**Comment by kirikak2** [comment]
Thanks for great changes!
